[project]
name = "google-ai-studio"
version = "0.1.0"
description = "first time using google ai studio"
authors = [{ name = "Jeerasak Ananta", email = "jeerasakananta@example.com" }]
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["dotenv>=0.9.9", "google-genai>=1.16.1"]
