services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin@admin.com
      - N8N_HOST=yourdomain.com
      - WEBHOOK_TUNNEL_URL=https://yourdomain.com
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
