services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      # Default HTTP Port
      - "80:80/tcp"
      # Default HTTPs Port. FTL will generate a self-signed certificate
      - "443:443/tcp"
      # Uncomment the below if using Pi-hole as your DHCP Server
      #- "67:67/udp"
    environment:
      TZ: ${TZ}
      FTLCONF_webserver_api_password: ${PIHOLE_API_PASSWORD}
      WEBPASSWORD: ${WEBPASSWORD}
      DNS1: ${DNS1}
      DNS2: ${DNS2}
      PIHOLE_email: ${PIHOLE_EMAIL}
      API_KEY: ${API_KEY}
      INTERFACE_IP: ${INTERFACE_IP}
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole:/etc/pihole'
      # Uncomment if you have custom dnsmasq config files that you want to persist.
      #- './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped