services:
  homeassistant:
    container_name: home-assistant
    image: ghcr.io/home-assistant/home-assistant:latest
    volumes:
      - ./.config:/config  # Store configuration in a local folder
    environment:
      - TZ=Asia/Bangkok  # Set timezone to Thailand
    ports:
      - "8123:8123"
    restart: unless-stopped
    privileged: true
    network_mode: host  # Required for some integrations like Bluetooth

volumes:
  config:

