services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    environment:
      - ADMIN_PASSWORD=adminadmin  # (Optional, for added security)
      - TZ=Asia/Bangkok  # Set your timezone
      
volumes:
  portainer_data:

networks:
  portainer_network:
    driver: bridge