services:
  excalidraw:
    container_name: excalidraw
    image: excalidraw/excalidraw
    ports:
      - "3002:3000"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:3000/api
    restart: always
    volumes:
      - excalidraw_data:/usr/src/app/data

volumes:
  excalidraw_data: